configfile: 'config/config.yaml'

rule all:
    input:
        'results/samtools_usage.pdf'

module mk_in:
    snakefile:
        'rules/mk_in.smk'
    config:
        config

module get_resources:
    snakefile:
        'rules/get_res.smk'
    config:
        config

module mk_graph:
    snakefile:
        'rules/graph_creation.smk'
    config:
        config

use rule * from mk_in
use rule * from get_resources
use rule * from mk_graph