#!/bin/bash
#SBATCH --job-name=test
#SBATCH --account=publicgrp
#SBATCH --partition=low
#SBATCH --output=jobs/%j_check/%x.out
#SBATCH --err=jobs/%j_check/%x.err
#SBATCH --cpus-per-task=1
#SBATCH --mem=1250MB
#SBATCH --time=15:00

source /etc/profile
module load conda
source $(conda info --base)/etc/profile.d/conda.sh
conda activate snakehive

rm -r .snakemake/conda/*
snakemake --profile slurm --forceall