configfile: 'config/config.yaml'

rule all:
	input:
		expand('results/blast_out{num}.txt', num=config['trials'])

module mk_in:
	snakefile:
		'rules/mk_in.smk'
	config:
		config

module blast:
	snakefile:
		'rules/blast.smk'

use rule * from mk_in
use rule * from blast