configfile: 'config/config.yaml'

trials = []
for n in range(config['trials']): trials.append(n+1)

rule all:
	input:
		expand('results/blast_out{num}.txt', num=trials)

module mk_in:
	snakefile:
		'rules/mk_in.smk'
	config:
		config

module blast:
	snakefile:
		'rules/blast.smk'

use rule * from mk_in
use rule * from blast