configfile: 'config/config.yaml'

rule all:
    input:
        'results/01_output.bam'

module mk_input:
    snakefile:
        'rules/mk_input.smk'
    config:
        config

module mk_output:
    snakefile:
        'rules/mk_output.smk'

use rule * from mk_input
use rule * from mk_output

